# Project: Scanf calismasi
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = scanfcalisma.o
LINKOBJ  = scanfcalisma.o
LIBS     = -L"D:/Dec-C++/Dev-Cpp/MinGW64/lib" -L"D:/Dec-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Dec-C++/Dev-Cpp/MinGW64/include" -I"D:/Dec-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dec-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dec-C++/Dev-Cpp/MinGW64/include" -I"D:/Dec-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dec-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dec-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Scanf calismasi.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

scanfcalisma.o: scanfcalisma.c
	$(CC) -c scanfcalisma.c -o scanfcalisma.o $(CFLAGS)
